version: "3.8"

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "${OPEN_WEBUI_PORT}:8080"
    environment:
      - "OLLAMA_BASE_URL=http://${OLLAMA_IP}:${OLLAMA_PORT}"
      - "OPENAI_API_KEYS=${OPENAI_API_KEY}"
      - "ENABLE_MODEL_FILTER=True"
      - "MODEL_FILTER_LIST=${MODEL_FILTER_LIST}"
    volumes:
      - ./volumes/data:/app/backend/data
      - ./litellm/config.yaml:/app/backend/data/litellm/config.yaml
    restart: always
